export const MENU_ITEMS = [
  // Principales
  {
    id: 1,
    name: "Cochinita Pibil Tradicional",
    description: "Carne de cerdo marinada en achiote, cocida lentamente en hojas de plátano",
    price: 8.99,
    image: "/cochinita-pibil-traditional.jpg",
    category: "Principales",
    calories: 450,
    portion: "200g",
    ingredients: "Cerdo, achiote, cítricos, hojas de plátano, especias yucatecas",
    details:
      "Auténtica receta yucateca marinada por 12 horas y cocida lentamente. Servida con cebolla morada y cilantro fresco.",
  },
  {
    id: 2,
    name: "Orden de Tacos (3)",
    description: "Tres tacos de cochinita pibil con cebolla morada y cilantro",
    price: 6.99,
    image: "/tacos-cochinita-pibil.jpg",
    category: "Principales",
    calories: 380,
    portion: "3 tacos",
    ingredients: "Tortillas de maíz, cochinita pibil, cebolla morada, cilantro",
    details: "Tacos tradicionales con tortillas hechas a mano, rellenas de cochinita pibil jugosa.",
  },
  {
    id: 3,
    name: "Burrito de Cochinita",
    description: "Burrito relleno de cochinita pibil, arroz y frijoles",
    price: 7.99,
    image: "/burrito-cochinita.jpg",
    category: "Principales",
    calories: 520,
    portion: "280g",
    ingredients: "Tortilla de harina, cochinita pibil, arroz, frijoles, queso",
    details: "Burrito abundante relleno de cochinita pibil, arroz blanco y frijoles refritos. Perfecto para llevar.",
  },
  {
    id: 4,
    name: "Pibil Quesadilla",
    description: "Quesadilla rellena de cochinita pibil y queso Oaxaca",
    price: 5.99,
    image: "/quesadilla-pibil.jpg",
    category: "Principales",
    calories: 420,
    portion: "220g",
    ingredients: "Tortilla de maíz, cochinita pibil, queso Oaxaca, cebolla",
    details: "Quesadilla crujiente con queso Oaxaca derretido y cochinita pibil suculenta.",
  },
  {
    id: 9,
    name: "Pibil Enchiladas (3)",
    description: "Enchiladas rellenas de cochinita pibil con salsa roja y crema",
    price: 8.49,
    image: "/enchiladas-cochinita-pibil.jpg",
    category: "Principales",
    calories: 480,
    portion: "3 enchiladas",
    ingredients: "Tortillas, cochinita pibil, salsa roja, crema mexicana, queso",
    details: "Enchiladas bañadas en salsa roja casera, cubiertas con crema mexicana y queso fresco.",
  },
  {
    id: 10,
    name: "Pibil Sándwich",
    description: "Sándwich con pan de la casa, cochinita pibil y encurtido yucateco",
    price: 7.49,
    image: "/sandwich-cochinita.jpg",
    category: "Principales",
    calories: 400,
    portion: "250g",
    ingredients: "Pan de la casa, cochinita pibil, encurtido yucateco, mayonesa",
    details: "Sándwich preparado con pan tostado, cochinita pibil y encurtido yucateco tradicional.",
  },
  {
    id: 11,
    name: "Plato de Cochinita Mixto",
    description: "Combinación de cochinita pibil, arroz, frijoles y tortillas",
    price: 9.99,
    image: "/plato-mixto-cochinita.jpg",
    category: "Principales",
    calories: 580,
    portion: "400g",
    ingredients: "Cochinita pibil, arroz blanco, frijoles refritos, tortillas, encurtido",
    details: "El plato completo yucateco: cochinita pibil, arroz, frijoles y tortillas hechas al momento.",
  },
  // Sopas
  {
    id: 5,
    name: "Sopa de Lima",
    description: "Auténtica sopa yucateca con pollo y lima agria",
    price: 4.99,
    image: "/sopa-de-lima.jpg",
    category: "Sopas",
    calories: 280,
    portion: "300ml",
    ingredients: "Caldo de pollo, pollo deshebrado, lima agria, tortillas fritas",
    details: "Tradicional sopa yucateca con pollo tierno, lima agria fresca y tortillas crujientes.",
  },
  {
    id: 12,
    name: "Caldo de Res",
    description: "Tradicional caldo con res, verduras y hierbas aromáticas",
    price: 5.49,
    image: "/caldo-de-res.jpg",
    category: "Sopas",
    calories: 320,
    portion: "320ml",
    ingredients: "Res, verduras, cebolla, cilantro, especias",
    details: "Caldo casero con res de calidad, cocinado lentamente con verduras frescas.",
  },
  {
    id: 13,
    name: "Consomé de Pollo",
    description: "Consomé claro con pollo deshebrado, cebolla y cilantro",
    price: 4.49,
    image: "/consome-pollo.jpg",
    category: "Sopas",
    calories: 200,
    portion: "300ml",
    ingredients: "Caldo claro, pollo deshebrado, cebolla, cilantro, limón",
    details: "Consomé light y reconfortante, perfecto para acompañar cualquier platillo.",
  },
  {
    id: 14,
    name: "Sopa de Maíz",
    description: "Sopa cremosa de maíz fresco con epazote y queso",
    price: 4.99,
    image: "/sopa-maiz-yucateca.jpg",
    category: "Sopas",
    calories: 350,
    portion: "320ml",
    ingredients: "Maíz fresco, crema, epazote, queso, cebolla",
    details: "Sopa cremosa con maíz dulce del día, epazote aromático y queso derretido.",
  },
  // Acompañamientos
  {
    id: 6,
    name: "Arroz Blanco",
    description: "Arroz blanco de la casa, acompañamiento perfecto",
    price: 2.99,
    image: "/arroz-blanco.jpg",
    category: "Acompañamientos",
    calories: 200,
    portion: "150g",
    ingredients: "Arroz blanco, caldo de pollo, cebolla, aceite de oliva",
    details: "Arroz blanco fluffy preparado con caldo casero y especias finas.",
  },
  {
    id: 7,
    name: "Frijoles Refritos",
    description: "Frijoles negros refritos con queso y cilantro",
    price: 2.49,
    image: "/frijoles-refritos.jpg",
    category: "Acompañamientos",
    calories: 180,
    portion: "150g",
    ingredients: "Frijoles negros, queso, cilantro, cebolla, aceite",
    details: "Frijoles negros refritos con queso Oaxaca derretido y cilantro fresco.",
  },
  {
    id: 15,
    name: "Tortillas de Maíz (6)",
    description: "Tortillas recién hechas de maíz, perfectas para cualquier platillo",
    price: 1.99,
    image: "/tortillas-maiz.jpg",
    category: "Acompañamientos",
    calories: 150,
    portion: "6 tortillas",
    ingredients: "Maíz, agua, sal",
    details: "Tortillas hechas al momento en casa, solo maíz y tradición.",
  },
  {
    id: 16,
    name: "Encurtido Yucateco",
    description: "Mezcla de vegetales encurtidos con habanero y vinagre",
    price: 2.99,
    image: "/encurtido-yucateco.jpg",
    category: "Acompañamientos",
    calories: 80,
    portion: "150g",
    ingredients: "Cebolla, zanahoria, habanero, vinagre, especias",
    details: "Encurtido tradicional yucateco picoso y refrescante, acompañamiento perfecto.",
  },
  {
    id: 17,
    name: "Guacamole Fresco",
    description: "Guacamole preparado al momento con aguacate, limón y cilantro",
    price: 3.49,
    image: "/guacamole-fresco.jpg",
    category: "Acompañamientos",
    calories: 160,
    portion: "120g",
    ingredients: "Aguacate, limón, cilantro, cebolla, sal",
    details: "Guacamole preparado al momento con aguacates frescos y cítricos naturales.",
  },
  // Bebidas
  {
    id: 8,
    name: "Agua de Jamaica",
    description: "Bebida refrescante tradicional yucateca",
    price: 1.99,
    image: "/agua-jamaica.jpg",
    category: "Bebidas",
    calories: 60,
    portion: "350ml",
    ingredients: "Jamaica, azúcar, agua, hielo",
    details: "Bebida tradicional yucateca refrescante hecha con flores de jamaica naturales.",
  },
  {
    id: 18,
    name: "Agua de Horchata",
    description: "Bebida dulce de arroz con leche y canela",
    price: 1.99,
    image: "/agua-horchata.jpg",
    category: "Bebidas",
    calories: 180,
    portion: "350ml",
    ingredients: "Arroz, leche, canela, azúcar, agua",
    details: "Horchata casera hecha con arroz, leche y canela. Deliciosamente refrescante.",
  },
  {
    id: 19,
    name: "Refresco Mexicano",
    description: "Refresco embotellado de marca mexicana",
    price: 2.49,
    image: "/refresco-mexicano.jpg",
    category: "Bebidas",
    calories: 140,
    portion: "500ml",
    ingredients: "Bebida carbonatada, azúcar, saborizantes naturales",
    details: "Refresco embotellado frío, sabores mexicanos tradicionales.",
  },
  {
    id: 20,
    name: "Cerveza Corona",
    description: "Cerveza mexicana fría",
    price: 3.49,
    image: "/cerveza-corona.jpg",
    category: "Bebidas",
    calories: 148,
    portion: "355ml",
    ingredients: "Malta, lúpulo, levadura, agua",
    details: "Cerveza mexicana premium, fría y refrescante para disfrutar con tus platillos.",
  },
  {
    id: 21,
    name: "Jugo Natural",
    description: "Jugo fresco del día - naranja, piña o sandía",
    price: 2.99,
    image: "/jugo-natural-fresco.jpg",
    category: "Bebidas",
    calories: 110,
    portion: "350ml",
    ingredients: "Frutas frescas de temporada, agua, azúcar",
    details: "Jugo 100% natural hecho del día con frutas frescas de temporada.",
  },
]
